clear all; close all; clc;

first = 1;
last  = 50;
channel = 1;

K = 32;
fs = 256;
fc = 32;

types = [       ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "cell",     ...
    "string"];

names = [
    "deltaDelta"    ...
    "deltaTheta"    ...
    "deltaAlpha"    ...
    "deltaBeta"     ...
    "thetaTheta"    ...
    "thetaAlpha"    ...
    "thetaBeta"     ...
    "alphaAlpha"    ...
    "alphaBeta"     ...
    "Annotations"];

sz = [0 numel(names)];

QPC = table('Size',sz,'VariableTypes',types,'VariableNames',names);

for i = first:1:last
    txt = sprintf("SN%03d.edf",i);
    if ~isfile(txt) continue; end

    fprintf("Loading EDF files for patient %d ... ",i);
    Z = loadEDF(i);
    fprintf("OK\n");

    fprintf("Estimating bicoherence matrix ... ");
    [X,f] = bicEEG(Z,K,fs,fc,channel,"fast");
    fprintf("OK\n");

    fprintf("Locating bicoherence peaks ... ");
    QPC = [QPC; findQPC(X,f)];
    fprintf("OK\n");

    fprintf("\n");
end


weightHist(QPC,f);